* 故事背景
  蓝色北京，假游戏设计师，虚拟世界，虚拟人动物事物
  最后倒计时，什么也不做/登录账号输入代码->世界交换，骗局
  
* 剧情
有人吗？
有人吗？
F***！什么破信号
呃，这破烂儿居然还屏蔽敏感词？这帮程序员的工资还真没白领。
（「什么情况」）

啊吾力小魔仙！总算是！
没想到真能联系上，还是拜菩萨好使，看来以后我要改信仰了。
（「你谁啊」）

我叫John，是一名软件工程师，不过这都不重要。
重要的是，我现在遇到点麻烦..
对..简直太麻烦了，我需要你的帮助
我被困在游戏里了！
（延迟）
最怕空气突然安静
（「拜拜」）

等一下！
听我说完
说实话，我原本也不信
发生了什么我根本不记得，但我觉得我应该晕了，总之，醒来我就在这儿了
我以为自己被绑架，毕竟刚卖了房，手头还是趁点钱的，嗯
但醒来之后我发现身上既没有绳子，嘴里也没有抹布
我仔细检查了肾的位置，除了两年前阑尾炎的刀疤之外，没有多余的切口
直到我发现身上有个通讯器
开机界面写着这么一句话，等下，我转发给你。
--- 欢迎来到BlueSpace游戏世界，本游戏由反人类工作室制作，在这里你将在一个真实的游戏世界中完成冒险，探索游戏规则 ---
--- 首先请使用通讯器联系一个人辅助你你完成游戏 ---
。。。。。。
我鼓捣了半天这玩意儿，终于联系到了你，真没想到这玩意儿还能联系到现实世界的人。
这下你该信了吧
（「你在哪」「不信」）

--- 不信
我的周围时不时会响起bgm
这下你该信了吧
（「你在哪」「不信」）

--- 不信
我的眼前居然还会掉帧
这下你该信了吧
（「你在哪」「不信」）

--- 不信
我现在口袋里有$5000初始金币
这下你该信了吧
（「你在哪」「不信」）

--- 不信
去死吧，没法聊
（「你在哪」）

好问题。能问出这个问题，我觉得我浪费了一下午时间联系了一个白痴。
我在附近逛游了2个小时，大叫了42次，基本可以确定是
这儿很无聊
这像是个荒岛，荒岛求生，多无聊的剧本
我的旁边有一个废弃的工厂，我还没有进去过，因为不知道会有什么豺狼虎豹，但应该也没有人
嗯，就我一个，闻到了吗，自由的气息，在一个荒岛上
hooray!
要不是因为我对这地方不太熟，我还真打算留下来养老


（「那怎么办」）
看在上帝的份上，你不打算替我报警吗？
我不想再打这么多字了，你根本不知道这个输入法有多么的蛋疼
（「911」）
du...
du...
du...
这里是警察局，有什么情况吗？
（「有人困在游戏里了」）
哦，他是未成年人吗？
（「我想不是」）
那这个不属于我们的管辖范围
不过您不用担心，这种情况很常见，久了他就会出来的
du.du.du.du..
(「警察说不用担心」「警察不管」)

--- 不用担心
靠谱！谢谢，我为我刚刚过激的言辞向你道歉
不过，说实话我现在很不淡定，现在天快黑了，我打算先睡一觉，等天亮了去工厂里面看看有什么东西
等明天早上再联系
--- 不管
WHAT???!!! 这帮蠢货，我的税都白交了吗
算了，天快黑了，我打算先睡一觉，等天亮了去工厂里面看看有什么东西再说
等明天早上再联系
(「好」)


睡的真不错，我感觉脸上皱纹都少了（实际上我一晚上没合眼。）
我现在去工厂里看看。待会我们再联系。

收获颇丰。工厂里有食物和水，一瓶安眠药，一本playboy，都是生活的必需品，另外我还发现了一张地图，画工堪称神工鬼斧。
在仔细研究了5秒之后我就确定了自己的位置，因为这里毕竟荒的像程序员的顶。
地图的右上角有一个房子的标识。
没错，有房子！
没准是个小镇！
我总是这么乐观。
我打算去那儿看一看，虽然我现在很想出去，但我更想先有食物和水，警察肯定会想办法救出我，而我最重要的就是活到那个时候，这种基本的求生常识我还是有的。我果然是天才。
从地图上看，这个小镇离我大约...50公里，现在走大概傍晚可以到。
（「现在走」/「再逛逛」）

--- 现在走
我出发了，等我到了那再联系吧。
--- 再逛逛
对，这景色这么美，可得好好欣赏，就当去趟罗布泊了
逛完了，现在走吗？
（「现在走」「再逛逛」）
对，这景色这么美，可得好好欣赏，就当去趟撒哈拉了
逛完了，现在走吗？
（「现在走」/「再逛逛」）
对，这景色这么美，可得好好欣赏，就当去趟冥王星了
逛完了，现在走吗？
（「现在走」/「再逛逛」）

（延迟）
那出发吧，一会再联系
啊哈！我面前居然出现条河，惊不惊喜。你无法体会我此刻的激动的心情。
地图上并没有这条河，我现在怀疑那个小镇存在的可能性。
真想把地图烧了，真的，我现在口袋里就有打火机。
不管怎样，我得想办法过去。
一种办法是游过去，水并不是很急。或者，沿河走一段，既然是个游戏，我想肯定是有桥的，但是肯定会耽误时间。
（「游过去」/「绕过去」）

-- 绕过去
我可是我们村儿的游泳冠军，这样的河我一个猛子...就淹死了，你说的对，我还是绕道的好
话说你要是想玩这个游戏可以用我的账号
用户名是 我的祖国
密码是 1tdhblkfcdhx2a
不不，这可不是乱码
来，跟我唱：一条大河～波浪宽，风吹稻花向两岸～
我走了1公里，别说桥了，岸边连块大点的石头都没有
算了，等我找到桥了再联系吧
（「好」）
（延迟）

--- 游过去
我可是我们村儿的游泳冠军，这样的河我一猛子...就能到对岸
话说你要是想玩这个游戏可以用我的账号
用户名是 我的祖国
密码是 1tdhblkfcdhx2a
不不，这可不是乱码
来，跟我唱：一条大河～波浪宽，风吹稻花向两岸～
我要以最擅长的狗刨式游到对岸了，出发了，等到对岸再联系吧
（「好」）


Hi，我现在有一个坏消息一个好消息
好消息是，已经到对岸了
坏消息是，我的包掉进了河里，所以现在食物储备是Null
我要不要去试着把包捞上来
（「要」「不要」）

--- 要
突然想起来，包里还有我上个月买的彩票呢，必须捞！
等我的好消息！
（延迟）
打捞失败。我自己也被冲走了
不过我还算清楚现在的位置
我必须尽快走到那个有房子地方，现在真的是又累又饿，或许有个好心的大婶儿，给我端上一碗热腾腾的炝锅汤面。
因为打捞浪费了不少时间，天要黑了，看来今晚真的要在野外过夜了。
不过我至少要生个火，烤烤衣服，而且万一有野兽呢，我可不想一觉醒来变成某个物种的食物储备，还好我有打火机，哈哈，以后谁都不要再劝我戒烟。
好了，我睡了，希望明天早晨我还是个完整的自己，晚安
（「晚安」）

--- 不要
对啊，一个包而已，无非就是全部的口粮和饮用水，扔就扔了，省的我也被水冲走。
我必须尽快走到那个有房子地方，或许有个好心的大婶儿，给我端上一碗热腾腾的炝锅汤面。
因为绕道，天要黑了，看来今晚真的要在野外过夜了。
不过我至少要生个火，我可不想一觉醒来变成某个物种的食物储备，还好我有打火机，以后谁都不要再劝我戒烟。
好了，我睡了，希望明天早晨我还是个完整的自己，晚安
（「晚安」）
（延迟）

早安，昨晚睡的不错。
起床后我先检查了我的胳膊、腿和肾，都在，不过我的肚子饿的咕咕叫了。
今天是最后一段路，应该很快就能到达那所房子了。
出发，回头联系。
（延迟）

我到了，跟我想象的别墅有点距离啊，额不..这根本就是一个破瓦房！
不过这种荒凉的地方有一座房子也实在是奇怪，建它的人是想来这度假吗
既然来了，还是进去看看吧
但是我并不会放弃跟你吐槽，主要是为了让你知道我还活着，我现在真的又累又饿，就要到极限了
我要开门了
嗯，里面毛都没有，只有一个向下的楼梯不知道通到哪儿
以我5.2的视力，我看到下面有成堆的金币，还有一个守墓的血尸，后悔没带上我的黑驴蹄子。
好吧，下面可能什么都有，就是没有光。
我要不要再逛一逛，不着急下去吧
（「逛一逛」「现在下去」）

--- 逛一逛
对对，虽然没有食物也没有体力，但没准能逛出一只野兔
逛完了，现在下去吗？
（「逛一逛」「现在下去」）
--- 逛一逛
对对，虽然没有食物也没有体力，但没准能逛出一只野猪
逛完了，现在下去吗？
（「逛一逛」「现在下去」）
--- 逛一逛
对对，虽然没有食物也没有体力，但没准能逛出一只野驴
逛完了，现在下去吗？
（「逛一逛」「现在下去」）
--- 逛一逛
野驴！真的有！
白痴，你还真信了
（「现在下去」）


--- 现在下去
我要下去了。
说实话，我现在随时准备被一个突然跳出来的血尸掐断我的脖子
如果我死了，请把我的全部财产捐给我的祖国。
没准还能上报纸，「90后程序员沉迷游戏，莫名死亡，2千元遗产全部上交国家」
男默女泪
现在想想，能活到今天我靠的从来都是遵纪守法，先人后己
从来不曾偷税漏税
所以才这么穷，唉
这里真是黑的彻底，每下一层都要先用脚找找有没有台阶。
扶手上锈迹斑斑，这里似乎很久了
好了，一会再聊，下楼梯根本没法打字。

到底了，还好通讯器有点光，让我多看到了20公分
前面是个隧道...天啊，鬼知道我会遇上什么
你怕鬼吗，我小时候一个人在墓地里走，让我不害怕的方法就是默念希特勒
这人可比鬼吓人多了
我打算这回默念艾森豪威尔，毕竟是所谓的正派，更有底

好了，我正沿着墙壁，慢慢的走
一步...
两步...
知道我现在最不希望出现的是什么吗？
不是什么女鬼僵尸，而是...
岔路口!
好的好的，我就知道...现在右手边又出来一条路，我该怎么走？
（「右拐」/「直走」）

--- 右拐 --- 直走
你是随便选的对吧
其实无所谓，我是说，大不了看到面前有个异形吃人的时候，我就假装走错了房间
我觉得我走路的声音也足够把它招来了。
我走路为啥有这么大的声音啊
等等...
这声音好像不是我发出来的...
我后面有别人？！
我*！
嘘...别说话，我要先把通讯录的屏幕关了，拜拜。
（延迟）
声音小了，它好像去了另一个岔路。谢天谢地。
究竟是个什么玩意儿，吓死我了。
我还想是不是打猎的野人回家了
然后没打到吃的正在为今天的晚饭发愁
我要不要回去看看？
（「回去看」「继续走」）
...

--- 看
不好意思，要回去你回，这次我不打算听你的
(「嗯」)
--- 继续走
当然要继续走，我可不想主动送死。
(「嗯」)

话说我为什么要到这个鬼地方来，搞不好挂了怎么办，我养的猫还没有喂呢
前面好像有光，我觉得我快到出口了。
又是个门，里面有光。
我觉得我突然有了勇气。我要进去。一会再聊。

我跟你描述一下屋里的场景。
墙上有一块屏幕，下面是个控制台，这好像是个某个的控制室
我想研究一下。不过我的能力仅限于敲键盘和踹主机。
（「你不是程序员吗」「敲键盘试试」）

--- 程序员
是啊，但是我是一个很渣的程序员，一行代码都不会写。
（「敲键盘试试」）
--- 敲键盘
我敲了一下，屏幕亮了。
--- 欢迎来到BlueSpace游戏世界，本游戏由反人类工作室制作，在这里你将在一个真实的游戏世界中完成冒险，探索游戏规则 ---
--- 首先请使用通讯器联系一个人辅助你你完成游戏 ---
--- 游戏世界中死亡将回到初始情节，并清除全部记忆 ---
等等，如果死亡会重制记忆，但有没有可能我已经在这个世界很长时间了？
--- 找到游戏控制室并运行后台代码完成逃脱 ---

王八！？
门口突然出现很多只龟！！每一个都有人那么高，眼睛像一个洞，深的看不见低，骷髅一般。
隧道里好像还有很多，它们一个排一个，要冲进来！啊啊！

##¥%@！，我究竟是为什么要到这个鬼地方啊！
我勉强把门锁住了，但应该坚持不了太长时间。赶紧看看屏幕上，这是什么？
BlueSpace开发文档？！！
--- 1. BlueSpace.escape_character() 释放当前游戏角色 ---
--- 2. BlueSpace.kill_character() 复位当前游戏角色 ---

我列个去，这里居然有游戏后门！
是要写代码的样子。
不过代码好像用python写的，我不会，你能帮我操作吗？
（「你究竟是不是程序员」）

我不是说我一行代码都不会写嘛，幸亏有你在，帮我写一下吧，时间紧迫，那些丑八怪就要冲进来了！
(「输入python」进入调试窗口)

>>> starting BlueSpace console...
>>> Welcome to BlueSpace
（「import BlueSpace」「BlueSpace.escape_character()」「BlueSpace.kill_character()」）

>>> Error: BlueSpace class Not Found!

>>> BlueSpace successfully imported!

>>> BlueSpace.escape_character()
>>> 请输入该用户的账号：
>>> 请输入该用户的密码：
>>> reloading...
>>> [#--------------------]
>>> [#-----]
>>> [######]

啊！我的身体在消失！
哈哈！我终于要离开这个鬼地方了！！！
谢谢你，通讯器我会带着，回去继续和你联系！

连接断开...
重建连接...
对方通讯器已不在这个世界，连接断开...
对方通讯器已不在这个世界，连接断开...
对方通讯器已不在这个世界，连接断开...

（字幕）



